"""
Test script for Email Notification Service
Run this to verify email configuration before running the full extraction bot
"""
import asyncio
import sys
from pathlib import Path
from datetime import datetime

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent))

from src.services.email_notifications.outlook_mailer import send_email_async
from src.utils.load_yaml import (
    EXTRACTION_NOTIFICATIONS_ENABLED,
    NOTIFICATION_RECIPIENTS_TO,
    NOTIFICATION_RECIPIENTS_CC,
    OUTLOOK_CLIENT_ID,
    OUTLOOK_TENANT_ID,
    OUTLOOK_TOKEN_CACHE_PATH
)


async def test_simple_email():
    """Test 1: Send a simple text email"""
    print("\n" + "="*70)
    print("TEST 1: Simple Text Email")
    print("="*70)
    
    try:
        success = await send_email_async(
            subject="🧪 Test Email - Extraction Bot Email Service",
            body="Hello!\n\nThis is a simple text email test.\n\nIf you receive this, the email service is working!\n\nBest regards,\nExtraction Bot",
            to=NOTIFICATION_RECIPIENTS_TO[:1] if NOTIFICATION_RECIPIENTS_TO else ["test@example.com"],
            client_id=OUTLOOK_CLIENT_ID,
            tenant_id=OUTLOOK_TENANT_ID,
            cache_path=OUTLOOK_TOKEN_CACHE_PATH,
        )
        
        if success:
            print("✅ Simple email sent successfully!")
            return True
        else:
            print("❌ Failed to send simple email")
            return False
            
    except Exception as e:
        print(f"❌ Error sending simple email: {e}")
        import traceback
        traceback.print_exc()
        return False


async def test_html_email():
    """Test 2: Send an HTML formatted email"""
    print("\n" + "="*70)
    print("TEST 2: HTML Formatted Email")
    print("="*70)
    
    html_body = """
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; }
            .header { background-color: #0066cc; color: white; padding: 20px; text-align: center; border-radius: 5px; }
            .content { padding: 20px; background-color: #f9f9f9; border: 1px solid #ddd; margin-top: 10px; }
            table { width: 100%; border-collapse: collapse; margin-top: 10px; }
            th { background-color: #0066cc; color: white; padding: 10px; }
            td { padding: 10px; border-bottom: 1px solid #ddd; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🧪 HTML Email Test</h1>
        </div>
        <div class="content">
            <h2>Email Service Configuration Test</h2>
            <p>This is an HTML formatted email test from your Extraction Bot.</p>
            
            <table>
                <tr>
                    <th>Test Item</th>
                    <th>Status</th>
                </tr>
                <tr>
                    <td>HTML Formatting</td>
                    <td>✅ Working</td>
                </tr>
                <tr>
                    <td>Table Rendering</td>
                    <td>✅ Working</td>
                </tr>
                <tr>
                    <td>Styling</td>
                    <td>✅ Working</td>
                </tr>
            </table>
            
            <p style="margin-top: 20px; color: #666;">
                <strong>If you see this message with proper formatting, your email service is fully operational!</strong>
            </p>
        </div>
    </body>
    </html>
    """
    
    try:
        success = await send_email_async(
            subject="🎨 Test HTML Email - Extraction Bot",
            body=html_body,
            to=NOTIFICATION_RECIPIENTS_TO[:1] if NOTIFICATION_RECIPIENTS_TO else ["test@example.com"],
            client_id=OUTLOOK_CLIENT_ID,
            tenant_id=OUTLOOK_TENANT_ID,
            cache_path=OUTLOOK_TOKEN_CACHE_PATH,
        )
        
        if success:
            print("✅ HTML email sent successfully!")
            return True
        else:
            print("❌ Failed to send HTML email")
            return False
            
    except Exception as e:
        print(f"❌ Error sending HTML email: {e}")
        import traceback
        traceback.print_exc()
        return False


async def test_email_with_attachment():
    """Test 3: Send an email with attachment"""
    print("\n" + "="*70)
    print("TEST 3: Email with Attachment")
    print("="*70)
    
    # Create a test file
    test_file = Path("test_attachment.txt")
    test_file.write_text("This is a test attachment file.\n\nGenerated by: Extraction Bot Email Service Test\nDate: " + datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    
    try:
        success = await send_email_async(
            subject="📎 Test Email with Attachment - Extraction Bot",
            body="<h2>Attachment Test</h2><p>This email includes a test text file attachment.</p><p>If you receive the attachment, the file attachment feature is working correctly!</p>",
            to=NOTIFICATION_RECIPIENTS_TO[:1] if NOTIFICATION_RECIPIENTS_TO else ["test@example.com"],
            attachments=[test_file],
            client_id=OUTLOOK_CLIENT_ID,
            tenant_id=OUTLOOK_TENANT_ID,
            cache_path=OUTLOOK_TOKEN_CACHE_PATH,
        )
        
        if success:
            print("✅ Email with attachment sent successfully!")
            # Clean up test file
            test_file.unlink()
            return True
        else:
            print("❌ Failed to send email with attachment")
            # Clean up test file
            if test_file.exists():
                test_file.unlink()
            return False
            
    except Exception as e:
        print(f"❌ Error sending email with attachment: {e}")
        import traceback
        traceback.print_exc()
        # Clean up test file
        if test_file.exists():
            test_file.unlink()
        return False


async def test_full_notification():
    """Test 4: Send a sample extraction notification"""
    print("\n" + "="*70)
    print("TEST 4: Sample Extraction Notification")
    print("="*70)
    
    from src.services.email_notifications.extraction_notifier import send_extraction_success_notification
    from datetime import timedelta
    
    # Mock data for testing
    now = datetime.now()
    mock_portal_results = {
        "Medgulf": True,
        "Takaful": True,
        "Orient": False,
        "ADNIC": True,
    }
    
    mock_portal_timings = {
        "Medgulf": {
            "start": now,
            "end": now + timedelta(seconds=135),
            "duration": timedelta(seconds=135)
        },
        "Takaful": {
            "start": now + timedelta(seconds=135),
            "end": now + timedelta(seconds=240),
            "duration": timedelta(seconds=105)
        },
        "Orient": {
            "start": now + timedelta(seconds=240),
            "end": now + timedelta(seconds=270),
            "duration": timedelta(seconds=30)
        },
        "ADNIC": {
            "start": now + timedelta(seconds=270),
            "end": now + timedelta(seconds=390),
            "duration": timedelta(seconds=120)
        },
    }
    
    try:
        success = await send_extraction_success_notification(
            run_timestamp="TEST_20260223_143022",
            overall_start_time=now,
            overall_end_time=now + timedelta(seconds=390),
            portal_results=mock_portal_results,
            portal_timings=mock_portal_timings,
            db_upload_success=True,
            db_rows_inserted=1542,
            db_upload_duration=12.5,
            total_duration=390,
            portals_processed=list(mock_portal_results.keys()),
            pdf_report_path=None,  # No attachment in test
            recipients_to=NOTIFICATION_RECIPIENTS_TO[:1] if NOTIFICATION_RECIPIENTS_TO else ["test@example.com"],
            recipients_cc=NOTIFICATION_RECIPIENTS_CC[:1] if NOTIFICATION_RECIPIENTS_CC else [],
        )
        
        if success:
            print("✅ Full extraction notification sent successfully!")
            print("\n📊 Check your email to see the complete extraction report format!")
            return True
        else:
            print("❌ Failed to send extraction notification")
            return False
            
    except Exception as e:
        print(f"❌ Error sending extraction notification: {e}")
        import traceback
        traceback.print_exc()
        return False


async def main():
    """Run all tests"""
    print("\n" + "="*70)
    print("📧 EMAIL NOTIFICATION SERVICE - TEST SUITE")
    print("="*70)
    
    # Check configuration
    print("\n📋 Configuration Status:")
    print(f"   Notifications Enabled: {EXTRACTION_NOTIFICATIONS_ENABLED}")
    print(f"   Client ID: {OUTLOOK_CLIENT_ID[:20]}..." if OUTLOOK_CLIENT_ID else "   Client ID: NOT SET")
    print(f"   Tenant ID: {OUTLOOK_TENANT_ID[:20]}..." if OUTLOOK_TENANT_ID else "   Tenant ID: NOT SET")
    print(f"   Token Cache: {OUTLOOK_TOKEN_CACHE_PATH}")
    print(f"   TO Recipients: {NOTIFICATION_RECIPIENTS_TO}")
    print(f"   CC Recipients: {NOTIFICATION_RECIPIENTS_CC}")
    
    if not EXTRACTION_NOTIFICATIONS_ENABLED:
        print("\n⚠️  WARNING: Email notifications are DISABLED in config.yaml")
        print("   Set 'extraction_notifications.enabled: true' to enable")
        return
    
    if not NOTIFICATION_RECIPIENTS_TO:
        print("\n⚠️  WARNING: No TO recipients configured!")
        print("   Please add email addresses in config.yaml under:")
        print("   extraction_notifications.recipients.to_recipients")
        print("\n   Continuing with placeholder email for testing...")
    
    print("\n" + "="*70)
    print("🚀 STARTING TESTS")
    print("="*70)
    print("\nNote: On first run, a browser window will open for authentication.")
    print("Login with your Microsoft 365 account to authorize email sending.")
    print("\nPress Enter to continue...")
    input()
    
    # Run tests
    results = []
    
    # Test 1
    results.append(await test_simple_email())
    await asyncio.sleep(2)
    
    # Test 2
    results.append(await test_html_email())
    await asyncio.sleep(2)
    
    # Test 3
    results.append(await test_email_with_attachment())
    await asyncio.sleep(2)
    
    # Test 4
    results.append(await test_full_notification())
    
    # Summary
    print("\n" + "="*70)
    print("📊 TEST SUMMARY")
    print("="*70)
    print(f"   Simple Email:        {'✅ PASS' if results[0] else '❌ FAIL'}")
    print(f"   HTML Email:          {'✅ PASS' if results[1] else '❌ FAIL'}")
    print(f"   Email w/ Attachment: {'✅ PASS' if results[2] else '❌ FAIL'}")
    print(f"   Full Notification:   {'✅ PASS' if results[3] else '❌ FAIL'}")
    print("="*70)
    
    passed = sum(results)
    total = len(results)
    
    if passed == total:
        print(f"\n🎉 ALL TESTS PASSED ({passed}/{total})")
        print("\n✅ Your email notification service is fully operational!")
        print("   You can now run the extraction bot with confidence.")
    else:
        print(f"\n⚠️  SOME TESTS FAILED ({passed}/{total} passed)")
        print("\n   Please check the error messages above and:")
        print("   1. Verify your config.yaml settings")
        print("   2. Check Azure AD app permissions")
        print("   3. Ensure network connectivity")
        print("   4. Review EMAIL_NOTIFICATION_SETUP.md for troubleshooting")
    
    print("\n" + "="*70)


if __name__ == "__main__":
    asyncio.run(main())
